### ISSUE TITLE
Whatever happened to crom?

### ISSUE THREAD

**Issue by utanapishtim** [mbostock/crom-test-foo#1]
I've found refs and links but it looks like the project was stricken from the internet. Care to give a quick postmortem? Please, no worries about responding if no time.

**Comment by mbostock** [comment]
I received toxic feedback on my half-baked idea and lost interest.

**Comment by utanapishtim** [comment]
So sorry to hear! From all I read about it, it seemed like a very cool
idea. Thanks for getting back to me. Sorry the culture can be so fucking
toxic so often! Thank you for all the incredible work you've done and are
doing.
